// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhqgVNzm0p15W31Rb4ZzC_POKN5SxMDc',
    appId: '1:804956207376:web:2404eceac2e78302570d95',
    messagingSenderId: '804956207376',
    projectId: 'silentguard-8d104',
    authDomain: 'silentguard-8d104.firebaseapp.com',
    storageBucket: 'silentguard-8d104.firebasestorage.app',
    measurementId: 'G-7791DWBG6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCppB3N0IWLL_mHYuiFciGyUSoi6sCP0ww',
    appId: '1:804956207376:android:1a76ffb09a816789570d95',
    messagingSenderId: '804956207376',
    projectId: 'silentguard-8d104',
    storageBucket: 'silentguard-8d104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoCAd38QnwVCnOKWC4PVqPexnRV4E2W8',
    appId: '1:804956207376:ios:6145c0fb28682499570d95',
    messagingSenderId: '804956207376',
    projectId: 'silentguard-8d104',
    storageBucket: 'silentguard-8d104.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoCAd38QnwVCnOKWC4PVqPexnRV4E2W8',
    appId: '1:804956207376:ios:6145c0fb28682499570d95',
    messagingSenderId: '804956207376',
    projectId: 'silentguard-8d104',
    storageBucket: 'silentguard-8d104.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfhqgVNzm0p15W31Rb4ZzC_POKN5SxMDc',
    appId: '1:804956207376:web:23fa03c65a37d952570d95',
    messagingSenderId: '804956207376',
    projectId: 'silentguard-8d104',
    authDomain: 'silentguard-8d104.firebaseapp.com',
    storageBucket: 'silentguard-8d104.firebasestorage.app',
    measurementId: 'G-WPM0N62YSR',
  );
}
