import type { User, Alert, DashboardStats } from './types'

export const mockUsers: User[] = [
  { id: '1', name: 'Admin VinBus', role: 'admin', avatar: 'AD', shift: 'Hành chính' },
  { id: '2', name: 'Nguyễn Thị Lan', role: 'operator', avatar: 'NT', shift: 'Ca đêm' },
  { id: '3', name: 'Trần Văn Tài', role: 'driver', avatar: 'TV', shift: 'Ca đêm' },
]

export const mockAlerts: Alert[] = [
  {
    id: 'EVT-0042',
    busId: 'BUS-102',
    route: 'Tuyến 32',
    eventType: 'Fight',
    confidence: 92,
    timestamp: '22:08:42',
    status: 'pending',
    mttd: 18,
    camera: 'Camera 3',
    description: 'Hai người tiếp xúc mạnh · 3 frames liên tiếp',
  },
  {
    id: 'EVT-0041',
    busId: 'BUS-047',
    route: 'Tuyến 15',
    eventType: 'Fall',
    confidence: 78,
    timestamp: '22:01:15',
    status: 'pending',
    mttd: 24,
    camera: 'Camera 1',
    description: 'Người ngã xuống · tư thế bất thường',
  },
  {
    id: 'EVT-0040',
    busId: 'BUS-213',
    route: 'Tuyến 09',
    eventType: 'Fight',
    confidence: 88,
    timestamp: '21:55:03',
    status: 'confirmed',
    mttd: 22,
    camera: 'Camera 2',
    description: 'Xô xát giữa 2 hành khách',
    reviewedBy: 'NT',
    reviewedAt: '21:56:10',
  },
  {
    id: 'EVT-0039',
    busId: 'BUS-088',
    route: 'Tuyến 27',
    eventType: 'Fall',
    confidence: 55,
    timestamp: '21:43:22',
    status: 'rejected',
    mttd: 31,
    camera: 'Camera 1',
    description: 'Người cúi xuống lấy đồ (false positive)',
    reviewNote: 'Không phải té ngã, hành khách cúi nhặt đồ',
    reviewedBy: 'NT',
    reviewedAt: '21:45:00',
  },
  {
    id: 'EVT-0038',
    busId: 'BUS-102',
    route: 'Tuyến 32',
    eventType: 'Fall',
    confidence: 85,
    timestamp: '21:30:11',
    status: 'confirmed',
    mttd: 20,
    camera: 'Camera 2',
    description: 'Hành khách trượt ngã khi xe phanh gấp',
    reviewedBy: 'NT',
    reviewedAt: '21:31:45',
  },
]

export const mockDashboardStats: DashboardStats = {
  totalAlerts: 42,
  confirmed: 30,
  rejected: 10,
  pending: 2,
  changeFromYesterday: 8,
  alertsByDay: [
    { date: 'T2', fall: 3, fight: 2 },
    { date: 'T3', fall: 5, fight: 4 },
    { date: 'T4', fall: 2, fight: 6 },
    { date: 'T5', fall: 4, fight: 3 },
    { date: 'T6', fall: 6, fight: 5 },
    { date: 'T7', fall: 3, fight: 7 },
    { date: 'CN', fall: 5, fight: 3 },
  ],
  topBuses: [
    { busId: 'BUS-102', count: 8 },
    { busId: 'BUS-047', count: 6 },
    { busId: 'BUS-213', count: 4 },
    { busId: 'BUS-088', count: 3 },
  ],
}
